refactor code v17 (read description) getting Username of Null
adding to the Favortie Movie list is working at the moment, but when I click profile I'm getting error and nothing show in the screen but it add the movies to database in mongoDB

====================
TypeError: Cannot read property 'Username' of null
    at profile-view.jsx:45